name: Tests

on: [push]

jobs:
  test:
    name: Test
    runs-on: macos-10.15
    steps:
      - name: Install helpers
        run: |
          brew install xcodegen
          gem install xcpretty
      - name: Run tests
        run: |
          set -o pipefail
          xcodegen
          xcodebuild -project Test.xcodeproj -scheme TestApp -sdk iphonesimulator13.6 -destination "platform=iOS Simulator,OS=13.6,name=iPhone 11" test | xcpretty
